<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/style.css?">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/noticias.css?">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/secciones.css?">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/tabla.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/forms.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/edit.css">
    <base href="<?php echo BASE_URL ?>">
    <title>El Respawn de la Semana</title>
</head>

<body>
    <header class="top-bar">
        <h1>El Respawn de la semana</h1>
        <ul>
            <li><a class="link" href="secciones"><?php if ($user): ?>
                        <?= 'Administrar Secciones' ?>
                    <?php else: ?>
                        <?= 'Secciones' ?>
                    <?php endif ?>
                </a></li>
            <li><a class="link" href=""><?php if ($user): ?>
                        <?= 'Administrar Noticias' ?>
                    <?php else: ?>
                        <?= 'Noticias' ?>
                    <?php endif ?></a></li>
            <li><?php if ($user): ?>
                    <span class="welcomeMessage">Bienvenido, <?= $user->nombre; ?></span>
                    <a class="link" href="logout" aria-current="page" href="logout">Salir</a>
                <?php else: ?>
                    <a class="link" href="login" aria-current="page" href="login">Ingresar</a>
                <?php endif; ?>
            </li>
        </ul>
    </header>
</body>

</html>