<?php require_once 'header.phtml' ?>
<main class="noticias">
    <?php foreach($noticias as $noticia){?>
    <article class="card-noticia">
        <img src="<?= $noticia->img?>" alt="">
        <h2><?= $noticia->titulo ?></h2>
        <small class="resume"><?= $noticia->resumen?></small>
        <small><?= $noticia->seccion?></small>
        <a class="btn-showMore" href="verNoticia/<?= $noticia->id ?>">Ver Más</a>
    </article>
    <?php } ?>
</main>
<?php require_once 'footer.phtml' ?>