<?php require_once 'header.phtml'?>
<?php if ($user): ?>
    <?php require_once 'adminSecciones.phtml'; ?>
<?php else: ?>
<main class="seccion-main">
    <?php foreach($secciones as $seccion){?> 
    <article class="seccion-card">
        <img src="<?= $seccion-> img_url?>">
        <h2><?= $seccion-> nombre ?></h2>
        <small><?= $seccion -> genero ?></small>
        <?php  
            $slug = trim($seccion->nombre);
            $slug = str_replace(' ', '-', $slug); ?>
        <a href="secciones/<?=$slug?>/noticias">Ver Noticias</a>
    </article>
    <?php } ?>
</main>
<?php endif; ?>
<?php require_once 'footer.phtml' ?>